#!/usr/bin/env python3
"""Advanced Engineering Calculator

Generated by GIMO multi-agent orchestration:
  - Orchestrator: Claude (plan, assembly, CLI menu)
  - Worker: Qwen 2.5-coder:3b via Ollama (functions, constants)
  - Worker: GPT-5 via codex-account (pending alternative)
"""

import math
import sys

# ==========================================================
# Physical Constants [Qwen Q1]
# ==========================================================

PHYSICAL_CONSTANTS = {
    "speed_of_light": (299792458.0, "m/s", "Speed of light in vacuum"),
    "planck": (6.62607015e-34, "J*s", "Planck constant"),
    "boltzmann": (1.380649e-23, "J/K", "Boltzmann constant"),
    "avogadro": (6.02214076e23, "1/mol", "Avogadro number"),
    "gas_constant": (8.314462618, "J/(mol*K)", "Universal gas constant"),
    "gravitational": (6.67430e-11, "m3/(kg*s2)", "Gravitational constant"),
    "electron_charge": (1.602176634e-19, "C", "Elementary charge"),
    "electron_mass": (9.1093837015e-31, "kg", "Electron mass"),
    "proton_mass": (1.67262192369e-27, "kg", "Proton mass"),
    "stefan_boltzmann": (5.670374419e-8, "W/(m2*K4)", "Stefan-Boltzmann constant"),
    "vacuum_permittivity": (8.8541878128e-12, "F/m", "Vacuum permittivity"),
    "vacuum_permeability": (1.25663706212e-6, "H/m", "Vacuum permeability"),
    "standard_gravity": (9.80665, "m/s2", "Standard gravity"),
    "standard_atmosphere": (101325.0, "Pa", "Standard atmosphere"),
    "water_density": (997.0, "kg/m3", "Water density at 25C"),
}

# ==========================================================
# Unit Conversions [Qwen Q2 + Q3]
# ==========================================================

def convert_temperature(value: float, from_unit: str, to_unit: str) -> float:
    """Convert temperature between C, F, K."""
    if from_unit == "C":
        celsius = value
    elif from_unit == "F":
        celsius = (value - 32) * 5 / 9
    elif from_unit == "K":
        celsius = value - 273.15
    else:
        raise ValueError(f"Unknown unit: {from_unit}")
    if to_unit == "C":
        return celsius
    elif to_unit == "F":
        return celsius * 9 / 5 + 32
    elif to_unit == "K":
        return celsius + 273.15
    else:
        raise ValueError(f"Unknown unit: {to_unit}")


def convert_length(value: float, from_unit: str, to_unit: str) -> float:
    """Convert length between m, km, mi, ft, in, cm, mm."""
    to_meters = {"m": 1.0, "km": 1000.0, "mi": 1609.344, "ft": 0.3048, "in": 0.0254, "cm": 0.01, "mm": 0.001}
    if from_unit not in to_meters or to_unit not in to_meters:
        raise ValueError(f"Unknown unit")
    meters = value * to_meters[from_unit]
    return meters / to_meters[to_unit]


def convert_mass(value: float, from_unit: str, to_unit: str) -> float:
    """Convert mass between kg, g, lb, oz, ton."""
    to_kg = {"kg": 1.0, "g": 0.001, "lb": 0.453592, "oz": 0.0283495, "ton": 1000.0}
    if from_unit not in to_kg or to_unit not in to_kg:
        raise ValueError(f"Unknown mass unit")
    kg = value * to_kg[from_unit]
    return kg / to_kg[to_unit]


def convert_pressure(value: float, from_unit: str, to_unit: str) -> float:
    """Convert pressure between Pa, kPa, MPa, bar, atm, psi."""
    to_pa = {"Pa": 1.0, "kPa": 1000.0, "MPa": 1e6, "bar": 1e5, "atm": 101325.0, "psi": 6894.757}
    if from_unit not in to_pa or to_unit not in to_pa:
        raise ValueError(f"Unknown pressure unit")
    pa = value * to_pa[from_unit]
    return pa / to_pa[to_unit]


def convert_energy(value: float, from_unit: str, to_unit: str) -> float:
    """Convert energy between J, kJ, MJ, cal, kcal, BTU, kWh, eV."""
    to_j = {"J": 1.0, "kJ": 1000.0, "MJ": 1e6, "cal": 4.184, "kcal": 4184.0, "BTU": 1055.06, "kWh": 3.6e6, "eV": 1.602176634e-19}
    if from_unit not in to_j or to_unit not in to_j:
        raise ValueError(f"Unknown energy unit")
    joules = value * to_j[from_unit]
    return joules / to_j[to_unit]


# ==========================================================
# Electrical Engineering [Qwen Q4]
# ==========================================================

def ohms_law(V=None, I=None, R=None):
    """Solve Ohm's law for the missing variable."""
    if V is None: return I * R
    if I is None: return V / R
    if R is None: return V / I
    raise ValueError("Provide exactly two of V, I, R")


def series_resistance(*resistors):
    """Total resistance in series."""
    return sum(resistors)


def parallel_resistance(*resistors):
    """Total resistance in parallel."""
    return 1.0 / sum(1.0/r for r in resistors)


def rc_time_constant(R, C):
    """RC circuit time constant (tau = R*C)."""
    return R * C


def rl_time_constant(R, L):
    """RL circuit time constant (tau = L/R)."""
    return L / R


def power_electrical(V=None, I=None, R=None):
    """Electrical power from any two of V, I, R."""
    if V is not None and I is not None: return V * I
    if V is not None and R is not None: return V**2 / R
    if I is not None and R is not None: return I**2 * R
    raise ValueError("Provide exactly two of V, I, R")


# ==========================================================
# Thermodynamics [Qwen Q5]
# ==========================================================

def ideal_gas_law(P=None, V=None, n=None, T=None):
    """Solve PV = nRT for the missing variable."""
    R = 8.314462618
    if P is None: return n * R * T / V
    if V is None: return n * R * T / P
    if n is None: return P * V / (R * T)
    if T is None: return P * V / (n * R)
    raise ValueError("Provide exactly three of P, V, n, T")


def carnot_efficiency(T_hot, T_cold):
    """Carnot efficiency (temperatures in Kelvin)."""
    return 1.0 - (T_cold / T_hot)


def heat_transfer_conduction(k, A, dT, L):
    """Fourier's law: Q = k*A*dT/L."""
    return k * A * dT / L


def heat_transfer_convection(h, A, dT):
    """Newton's law of cooling: Q = h*A*dT."""
    return h * A * dT


def heat_transfer_radiation(epsilon, A, T):
    """Stefan-Boltzmann radiation: Q = eps*sigma*A*T^4."""
    sigma = 5.670374419e-8
    return epsilon * sigma * A * T**4


# ==========================================================
# Fluid Mechanics + Structural Engineering [Qwen Q6]
# ==========================================================

def reynolds_number(rho, v, L, mu):
    """Reynolds number: Re = rho*v*L/mu."""
    return rho * v * L / mu


def bernoulli_pressure(rho, v1, P1, v2):
    """Bernoulli equation: P2 = P1 + 0.5*rho*(v1^2 - v2^2)."""
    return P1 + 0.5 * rho * (v1**2 - v2**2)


def flow_rate(A, v):
    """Volumetric flow rate: Q = A*v."""
    return A * v


def hydraulic_diameter(A, P):
    """Hydraulic diameter: Dh = 4*A/P."""
    return 4.0 * A / P


def stress(F, A):
    """Normal stress: sigma = F/A."""
    return F / A


def strain(dL, L):
    """Strain: epsilon = dL/L."""
    return dL / L


def youngs_modulus(stress_val, strain_val):
    """Young's modulus: E = sigma/epsilon."""
    return stress_val / strain_val


def moment_of_inertia_rect(b, h):
    """Moment of inertia for rectangle: I = b*h^3/12."""
    return (b * h**3) / 12.0


def moment_of_inertia_circle(r):
    """Moment of inertia for circle: I = pi*r^4/4."""
    return (math.pi * r**4) / 4.0


def bending_stress(M, y, I):
    """Bending stress: sigma = M*y/I."""
    return M * y / I


# ==========================================================
# Interactive CLI Menu [Claude Orchestrator]
# ==========================================================

def print_constants(constants):
    """Display all physical constants in a formatted table."""
    print()
    print(f"  {'Constant':<25s} {'Value':>15s} {'Unit':<15s} Description")
    print("  " + "-" * 80)
    for name, (val, unit, desc) in constants.items():
        print(f"  {name:<25s} {val:>15.6e} {unit:<15s} {desc}")


def get_float(prompt):
    """Safely get a float from user input."""
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("  Invalid number. Try again.")


def get_optional_float(prompt):
    """Get a float or None if empty."""
    val = input(prompt).strip()
    if not val:
        return None
    try:
        return float(val)
    except ValueError:
        print("  Invalid number.")
        return None


def menu_unit_conversions():
    """Unit conversion submenu."""
    print("\n  Unit Conversions:")
    print("    a) Temperature (C, F, K)")
    print("    b) Length (m, km, mi, ft, in, cm, mm)")
    print("    c) Mass (kg, g, lb, oz, ton)")
    print("    d) Pressure (Pa, kPa, MPa, bar, atm, psi)")
    print("    e) Energy (J, kJ, MJ, cal, kcal, BTU, kWh, eV)")
    sub = input("  Select [a-e]: ").strip().lower()
    converters = {
        "a": ("Temperature", convert_temperature),
        "b": ("Length", convert_length),
        "c": ("Mass", convert_mass),
        "d": ("Pressure", convert_pressure),
        "e": ("Energy", convert_energy),
    }
    if sub not in converters:
        print("  Invalid option.")
        return
    label, func = converters[sub]
    val = get_float(f"  Value: ")
    fr = input(f"  From unit: ").strip()
    to = input(f"  To unit: ").strip()
    try:
        result = func(val, fr, to)
        print(f"  Result: {val} {fr} = {result:.6g} {to}")
    except ValueError as e:
        print(f"  Error: {e}")


def menu_electrical():
    """Electrical engineering submenu."""
    print("\n  Electrical Engineering:")
    print("    a) Ohm's Law (V, I, R)")
    print("    b) Series Resistance")
    print("    c) Parallel Resistance")
    print("    d) RC Time Constant")
    print("    e) RL Time Constant")
    print("    f) Electrical Power")
    sub = input("  Select [a-f]: ").strip().lower()
    try:
        if sub == "a":
            V = get_optional_float("  V (or empty): ")
            I = get_optional_float("  I (or empty): ")
            R = get_optional_float("  R (or empty): ")
            result = ohms_law(V=V, I=I, R=R)
            label = "V" if V is None else ("I" if I is None else "R")
            print(f"  {label} = {result:.6g}")
        elif sub == "b":
            n = int(input("  Number of resistors: "))
            rs = [get_float(f"  R{i+1}: ") for i in range(n)]
            print(f"  Series R = {series_resistance(*rs):.6g} ohm")
        elif sub == "c":
            n = int(input("  Number of resistors: "))
            rs = [get_float(f"  R{i+1}: ") for i in range(n)]
            print(f"  Parallel R = {parallel_resistance(*rs):.6g} ohm")
        elif sub == "d":
            R = get_float("  R (ohm): ")
            C = get_float("  C (farad): ")
            print(f"  RC tau = {rc_time_constant(R, C):.6g} s")
        elif sub == "e":
            R = get_float("  R (ohm): ")
            L = get_float("  L (henry): ")
            print(f"  RL tau = {rl_time_constant(R, L):.6g} s")
        elif sub == "f":
            V = get_optional_float("  V (or empty): ")
            I = get_optional_float("  I (or empty): ")
            R = get_optional_float("  R (or empty): ")
            print(f"  Power = {power_electrical(V=V, I=I, R=R):.6g} W")
        else:
            print("  Invalid option.")
    except (ValueError, ZeroDivisionError) as e:
        print(f"  Error: {e}")


def menu_thermodynamics():
    """Thermodynamics submenu."""
    print("\n  Thermodynamics:")
    print("    a) Ideal Gas Law (PV = nRT)")
    print("    b) Carnot Efficiency")
    print("    c) Heat Transfer - Conduction")
    print("    d) Heat Transfer - Convection")
    print("    e) Heat Transfer - Radiation")
    sub = input("  Select [a-e]: ").strip().lower()
    try:
        if sub == "a":
            P = get_optional_float("  P in Pa (or empty): ")
            V = get_optional_float("  V in m3 (or empty): ")
            n = get_optional_float("  n in mol (or empty): ")
            T = get_optional_float("  T in K (or empty): ")
            result = ideal_gas_law(P=P, V=V, n=n, T=T)
            print(f"  Missing variable = {result:.6g}")
        elif sub == "b":
            Th = get_float("  T_hot (K): ")
            Tc = get_float("  T_cold (K): ")
            eff = carnot_efficiency(Th, Tc)
            print(f"  Carnot efficiency = {eff*100:.2f}%")
        elif sub == "c":
            k = get_float("  k (W/m*K): ")
            A = get_float("  A (m2): ")
            dT = get_float("  dT (K): ")
            L = get_float("  L (m): ")
            print(f"  Q = {heat_transfer_conduction(k, A, dT, L):.6g} W")
        elif sub == "d":
            h = get_float("  h (W/m2*K): ")
            A = get_float("  A (m2): ")
            dT = get_float("  dT (K): ")
            print(f"  Q = {heat_transfer_convection(h, A, dT):.6g} W")
        elif sub == "e":
            eps = get_float("  epsilon (0-1): ")
            A = get_float("  A (m2): ")
            T = get_float("  T (K): ")
            print(f"  Q = {heat_transfer_radiation(eps, A, T):.6g} W")
        else:
            print("  Invalid option.")
    except (ValueError, ZeroDivisionError) as e:
        print(f"  Error: {e}")


def menu_fluids():
    """Fluid mechanics submenu."""
    print("\n  Fluid Mechanics:")
    print("    a) Reynolds Number")
    print("    b) Bernoulli Pressure")
    print("    c) Flow Rate")
    print("    d) Hydraulic Diameter")
    sub = input("  Select [a-d]: ").strip().lower()
    try:
        if sub == "a":
            rho = get_float("  Density rho (kg/m3): ")
            v = get_float("  Velocity v (m/s): ")
            L = get_float("  Characteristic length L (m): ")
            mu = get_float("  Dynamic viscosity mu (Pa*s): ")
            Re = reynolds_number(rho, v, L, mu)
            regime = "Laminar" if Re < 2300 else ("Transitional" if Re < 4000 else "Turbulent")
            print(f"  Re = {Re:.2f} ({regime})")
        elif sub == "b":
            rho = get_float("  Density rho (kg/m3): ")
            v1 = get_float("  Velocity v1 (m/s): ")
            P1 = get_float("  Pressure P1 (Pa): ")
            v2 = get_float("  Velocity v2 (m/s): ")
            print(f"  P2 = {bernoulli_pressure(rho, v1, P1, v2):.6g} Pa")
        elif sub == "c":
            A = get_float("  Cross-section area A (m2): ")
            v = get_float("  Velocity v (m/s): ")
            print(f"  Q = {flow_rate(A, v):.6g} m3/s")
        elif sub == "d":
            A = get_float("  Cross-section area A (m2): ")
            P = get_float("  Wetted perimeter P (m): ")
            print(f"  Dh = {hydraulic_diameter(A, P):.6g} m")
        else:
            print("  Invalid option.")
    except (ValueError, ZeroDivisionError) as e:
        print(f"  Error: {e}")


def menu_structural():
    """Structural engineering submenu."""
    print("\n  Structural Engineering:")
    print("    a) Stress (sigma = F/A)")
    print("    b) Strain (epsilon = dL/L)")
    print("    c) Young's Modulus (E = sigma/epsilon)")
    print("    d) Moment of Inertia - Rectangle")
    print("    e) Moment of Inertia - Circle")
    print("    f) Bending Stress")
    sub = input("  Select [a-f]: ").strip().lower()
    try:
        if sub == "a":
            F = get_float("  Force F (N): ")
            A = get_float("  Area A (m2): ")
            print(f"  Stress = {stress(F, A):.6g} Pa")
        elif sub == "b":
            dL = get_float("  Change in length dL (m): ")
            L = get_float("  Original length L (m): ")
            print(f"  Strain = {strain(dL, L):.6g}")
        elif sub == "c":
            s = get_float("  Stress (Pa): ")
            e = get_float("  Strain: ")
            print(f"  Young's Modulus E = {youngs_modulus(s, e):.6g} Pa")
        elif sub == "d":
            b = get_float("  Width b (m): ")
            h = get_float("  Height h (m): ")
            print(f"  I = {moment_of_inertia_rect(b, h):.6g} m4")
        elif sub == "e":
            r = get_float("  Radius r (m): ")
            print(f"  I = {moment_of_inertia_circle(r):.6g} m4")
        elif sub == "f":
            M = get_float("  Bending moment M (N*m): ")
            y = get_float("  Distance from neutral axis y (m): ")
            Iv = get_float("  Moment of inertia I (m4): ")
            print(f"  Bending stress = {bending_stress(M, y, Iv):.6g} Pa")
        else:
            print("  Invalid option.")
    except (ValueError, ZeroDivisionError) as e:
        print(f"  Error: {e}")


def main():
    """Main interactive loop."""
    print()
    print("=" * 60)
    print("    Advanced Engineering Calculator")
    print("    Workers: Qwen 2.5-coder:3b (functions)")
    print("    Orchestrator: Claude (assembly + menu)")
    print("=" * 60)

    while True:
        print("\n  Categories:")
        print("    1. Physical Constants")
        print("    2. Unit Conversions")
        print("    3. Electrical Engineering")
        print("    4. Thermodynamics")
        print("    5. Fluid Mechanics")
        print("    6. Structural Engineering")
        print("    0. Exit")

        choice = input("\n  Select [0-6]: ").strip()

        if choice == "0":
            print("  Goodbye!")
            break
        elif choice == "1":
            print_constants(PHYSICAL_CONSTANTS)
        elif choice == "2":
            menu_unit_conversions()
        elif choice == "3":
            menu_electrical()
        elif choice == "4":
            menu_thermodynamics()
        elif choice == "5":
            menu_fluids()
        elif choice == "6":
            menu_structural()
        else:
            print("  Invalid choice. Please select 0-6.")


if __name__ == "__main__":
    main()
