# MANIFEST -- auto-generated with gimo_ prefixed names and /ops/ routes.
MANIFEST = [   {   'description': 'Get system status',
        'method': 'GET',
        'name': 'gimo_status',
        'params': [],
        'path': '/status'},
    {   'description': 'Get audit log',
        'method': 'GET',
        'name': 'gimo_audit_log',
        'params': [{'in': 'query', 'name': 'limit', 'required': False, 'type': 'integer'}],
        'path': '/ui/audit'},
    {   'description': 'Get security allowlist',
        'method': 'GET',
        'name': 'gimo_allowlist',
        'params': [],
        'path': '/ui/allowlist'},
    {   'description': 'List repositories',
        'method': 'GET',
        'name': 'gimo_repos_list',
        'params': [],
        'path': '/ops/repos'},
    {   'description': 'Get active repository',
        'method': 'GET',
        'name': 'gimo_repos_active',
        'params': [],
        'path': '/ops/repos/active'},
    {   'description': 'Open a repository',
        'method': 'POST',
        'name': 'gimo_repos_open',
        'params': [{'in': 'query', 'name': 'path', 'required': True, 'type': 'string'}],
        'path': '/ops/repos/open'},
    {   'description': 'Select active repository',
        'method': 'POST',
        'name': 'gimo_repos_select',
        'params': [{'in': 'query', 'name': 'path', 'required': True, 'type': 'string'}],
        'path': '/ops/repos/select'},
    {   'description': 'Revoke repository override',
        'method': 'POST',
        'name': 'gimo_repos_revoke',
        'params': [],
        'path': '/ops/repos/revoke'},
    {   'description': 'Get orchestration graph',
        'method': 'GET',
        'name': 'gimo_graph',
        'params': [],
        'path': '/ops/graph'},
    {   'description': 'Get security events',
        'method': 'GET',
        'name': 'gimo_security_events',
        'params': [],
        'path': '/ops/security/events'},
    {   'description': 'Resolve security event',
        'method': 'POST',
        'name': 'gimo_security_resolve',
        'params': [{'in': 'query', 'name': 'action', 'required': False, 'type': 'string'}],
        'path': '/ops/security/resolve'},
    {   'description': 'Get service status',
        'method': 'GET',
        'name': 'gimo_service_status',
        'params': [],
        'path': '/ops/service/status'},
    {   'description': 'Restart GIMO service',
        'method': 'POST',
        'name': 'gimo_service_restart',
        'params': [],
        'path': '/ops/service/restart'},
    {   'description': 'Stop GIMO service',
        'method': 'POST',
        'name': 'gimo_service_stop',
        'params': [],
        'path': '/ops/service/stop'},
    {   'description': 'Vitaminize a repository',
        'method': 'POST',
        'name': 'gimo_repos_vitaminize',
        'params': [{'in': 'query', 'name': 'path', 'required': True, 'type': 'string'}],
        'path': '/ops/repos/vitaminize'},
    {   'description': 'Create plan from UI',
        'method': 'POST',
        'name': 'gimo_plan_create',
        'params': [],
        'path': '/ui/plan/create'},
    {   'description': 'Reject a draft',
        'method': 'POST',
        'name': 'gimo_drafts_reject',
        'params': [{'in': 'path', 'name': 'draft_id', 'required': True, 'type': 'string'}],
        'path': '/ops/drafts/{draft_id}/reject'},
    {   'description': 'List providers',
        'method': 'GET',
        'name': 'gimo_providers_list',
        'params': [],
        'path': '/ops/providers'},
    {   'description': 'Add a provider',
        'method': 'POST',
        'name': 'gimo_providers_add',
        'params': [],
        'path': '/ops/providers'},
    {   'description': 'Remove a provider',
        'method': 'DELETE',
        'name': 'gimo_providers_remove',
        'params': [{'in': 'path', 'name': 'provider_id', 'required': True, 'type': 'string'}],
        'path': '/ops/providers/{provider_id}'},
    {   'description': 'Test provider connectivity',
        'method': 'POST',
        'name': 'gimo_providers_test',
        'params': [{'in': 'path', 'name': 'provider_id', 'required': True, 'type': 'string'}],
        'path': '/ops/providers/{provider_id}/test'},
    {   'description': 'List graph nodes',
        'method': 'GET',
        'name': 'gimo_nodes_list',
        'params': [],
        'path': '/ui/nodes'},
    {   'description': 'Compare model costs',
        'method': 'GET',
        'name': 'gimo_cost_compare',
        'params': [   {'in': 'query', 'name': 'model_a', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'model_b', 'required': True, 'type': 'string'}],
        'path': '/ui/cost/compare'},
    {   'description': 'Get Plan',
        'method': 'GET',
        'name': 'gimo_plan_get',
        'params': [],
        'path': '/ops/plan'},
    {   'description': 'Set Plan',
        'method': 'PUT',
        'name': 'gimo_plan_set',
        'params': [   {'in': 'body', 'name': 'id', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'title', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'workspace', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'created', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'objective', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'tasks', 'required': True, 'type': 'array'},
                      {'in': 'body', 'name': 'constraints', 'required': False, 'type': 'array'}],
        'path': '/ops/plan'},
    {   'description': 'List Drafts',
        'method': 'GET',
        'name': 'gimo_drafts_list',
        'params': [],
        'path': '/ops/drafts'},
    {   'description': 'Create Draft',
        'method': 'POST',
        'name': 'gimo_drafts_create',
        'params': [   {'in': 'body', 'name': 'prompt', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'context', 'required': False, 'type': 'object'},
                      {'in': 'body', 'name': 'objective', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'constraints', 'required': False, 'type': 'array'},
                      {   'in': 'body',
                          'name': 'acceptance_criteria',
                          'required': False,
                          'type': 'array'},
                      {'in': 'body', 'name': 'repo_context', 'required': False, 'type': 'object'},
                      {'in': 'body', 'name': 'execution', 'required': False, 'type': 'object'}],
        'path': '/ops/drafts'},
    {   'description': 'Get Draft',
        'method': 'GET',
        'name': 'gimo_drafts_get',
        'params': [{'in': 'path', 'name': 'draft_id', 'required': True, 'type': 'string'}],
        'path': '/ops/drafts/{draft_id}'},
    {   'description': 'Update Draft',
        'method': 'PUT',
        'name': 'gimo_drafts_update',
        'params': [   {'in': 'path', 'name': 'draft_id', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'prompt', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'content', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'context', 'required': False, 'type': 'string'}],
        'path': '/ops/drafts/{draft_id}'},
    {   'description': 'Reject Draft',
        'method': 'POST',
        'name': 'gimo_drafts_reject_ops',
        'params': [{'in': 'path', 'name': 'draft_id', 'required': True, 'type': 'string'}],
        'path': '/ops/drafts/{draft_id}/reject'},
    {   'description': 'Run Slice0 Pipeline',
        'method': 'POST',
        'name': 'gimo_slice0_pipeline',
        'params': [   {'in': 'query', 'name': 'prompt', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'repo_path', 'required': True, 'type': 'string'}],
        'path': '/ops/slice0-pipeline'},
    {   'description': 'Generate Structured Plan',
        'method': 'POST',
        'name': 'gimo_generate_plan',
        'params': [{'in': 'query', 'name': 'prompt', 'required': True, 'type': 'string'}],
        'path': '/ops/generate-plan'},
    {   'description': 'Generate Draft',
        'method': 'POST',
        'name': 'gimo_generate_draft',
        'params': [{'in': 'query', 'name': 'prompt', 'required': True, 'type': 'string'}],
        'path': '/ops/generate'},
    {   'description': 'Approve Draft',
        'method': 'POST',
        'name': 'gimo_drafts_approve',
        'params': [   {'in': 'path', 'name': 'draft_id', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'auto_run', 'required': False, 'type': 'string'}],
        'path': '/ops/drafts/{draft_id}/approve'},
    {   'description': 'List Approved',
        'method': 'GET',
        'name': 'gimo_approved_list',
        'params': [],
        'path': '/ops/approved'},
    {   'description': 'Get Approved',
        'method': 'GET',
        'name': 'gimo_approved_get',
        'params': [{'in': 'path', 'name': 'approved_id', 'required': True, 'type': 'string'}],
        'path': '/ops/approved/{approved_id}'},
    {   'description': 'List Runs',
        'method': 'GET',
        'name': 'gimo_runs_list',
        'params': [],
        'path': '/ops/runs'},
    {   'description': 'Create Run',
        'method': 'POST',
        'name': 'gimo_runs_create',
        'params': [{'in': 'body', 'name': 'approved_id', 'required': True, 'type': 'string'}],
        'path': '/ops/runs'},
    {   'description': 'Get Run',
        'method': 'GET',
        'name': 'gimo_runs_get',
        'params': [{'in': 'path', 'name': 'run_id', 'required': True, 'type': 'string'}],
        'path': '/ops/runs/{run_id}'},
    {   'description': 'Get Run Preview',
        'method': 'GET',
        'name': 'gimo_runs_preview',
        'params': [{'in': 'path', 'name': 'run_id', 'required': True, 'type': 'string'}],
        'path': '/ops/runs/{run_id}/preview'},
    {   'description': 'Cancel Run',
        'method': 'POST',
        'name': 'gimo_runs_cancel',
        'params': [{'in': 'path', 'name': 'run_id', 'required': True, 'type': 'string'}],
        'path': '/ops/runs/{run_id}/cancel'},
    {   'description': 'Execute Workflow',
        'method': 'POST',
        'name': 'gimo_workflows_execute',
        'params': [   {'in': 'body', 'name': 'workflow', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'initial_state', 'required': False, 'type': 'object'},
                      {   'in': 'body',
                          'name': 'persist_checkpoints',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'workflow_timeout_seconds',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/workflows/execute'},
    {   'description': 'List Workflow Checkpoints',
        'method': 'GET',
        'name': 'gimo_workflows_checkpoints',
        'params': [{'in': 'path', 'name': 'workflow_id', 'required': True, 'type': 'string'}],
        'path': '/ops/workflows/{workflow_id}/checkpoints'},
    {   'description': 'Resume Workflow',
        'method': 'POST',
        'name': 'gimo_workflows_resume',
        'params': [   {'in': 'path', 'name': 'workflow_id', 'required': True, 'type': 'string'},
                      {   'in': 'query',
                          'name': 'from_checkpoint',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/workflows/{workflow_id}/resume'},
    {   'description': 'Evals Run',
        'method': 'POST',
        'name': 'gimo_evals_run',
        'params': [   {'in': 'query', 'name': 'fail_on_gate', 'required': False, 'type': 'boolean'},
                      {'in': 'body', 'name': 'workflow', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'dataset', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'judge', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'gate', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'case_limit', 'required': False, 'type': 'string'}],
        'path': '/ops/evals/run'},
    {   'description': 'List Eval Runs',
        'method': 'GET',
        'name': 'gimo_evals_runs_list',
        'params': [   {'in': 'query', 'name': 'workflow_id', 'required': False, 'type': 'string'},
                      {'in': 'query', 'name': 'limit', 'required': False, 'type': 'integer'}],
        'path': '/ops/evals/runs'},
    {   'description': 'Get Eval Run',
        'method': 'GET',
        'name': 'gimo_evals_runs_get',
        'params': [{'in': 'path', 'name': 'run_id', 'required': True, 'type': 'integer'}],
        'path': '/ops/evals/runs/{run_id}'},
    {   'description': 'Create Eval Dataset',
        'method': 'POST',
        'name': 'gimo_evals_datasets_create',
        'params': [   {'in': 'query', 'name': 'version_tag', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'workflow_id', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'name', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'description', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'cases', 'required': False, 'type': 'array'}],
        'path': '/ops/evals/datasets'},
    {   'description': 'List Eval Datasets',
        'method': 'GET',
        'name': 'gimo_evals_datasets_list',
        'params': [   {'in': 'query', 'name': 'workflow_id', 'required': False, 'type': 'string'},
                      {'in': 'query', 'name': 'limit', 'required': False, 'type': 'integer'}],
        'path': '/ops/evals/datasets'},
    {   'description': 'Get Eval Dataset',
        'method': 'GET',
        'name': 'gimo_evals_datasets_get',
        'params': [{'in': 'path', 'name': 'dataset_id', 'required': True, 'type': 'integer'}],
        'path': '/ops/evals/datasets/{dataset_id}'},
    {   'description': 'Trust Query',
        'method': 'POST',
        'name': 'gimo_trust_query',
        'params': [],
        'path': '/ops/trust/query'},
    {   'description': 'Trust Dashboard',
        'method': 'GET',
        'name': 'gimo_trust_dashboard',
        'params': [{'in': 'query', 'name': 'limit', 'required': False, 'type': 'integer'}],
        'path': '/ops/trust/dashboard'},
    {   'description': 'Trust Suggestions',
        'method': 'GET',
        'name': 'gimo_trust_suggestions',
        'params': [{'in': 'query', 'name': 'limit', 'required': False, 'type': 'integer'}],
        'path': '/ops/trust/suggestions'},
    {   'description': 'Get Circuit Breaker Config',
        'method': 'GET',
        'name': 'gimo_trust_circuit_breaker_get',
        'params': [{'in': 'path', 'name': 'dimension_key', 'required': True, 'type': 'string'}],
        'path': '/ops/trust/circuit-breaker/{dimension_key}'},
    {   'description': 'Set Circuit Breaker Config',
        'method': 'PUT',
        'name': 'gimo_trust_circuit_breaker_set',
        'params': [   {'in': 'path', 'name': 'dimension_key', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'window', 'required': False, 'type': 'integer'},
                      {   'in': 'body',
                          'name': 'failure_threshold',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'recovery_probes',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'cooldown_seconds',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/trust/circuit-breaker/{dimension_key}'},
    {   'description': 'Trust Reset',
        'method': 'POST',
        'name': 'gimo_trust_reset',
        'params': [],
        'path': '/ops/trust/reset'},
    {   'description': 'Get Provider',
        'method': 'GET',
        'name': 'gimo_provider_get',
        'params': [],
        'path': '/ops/provider'},
    {   'description': 'Set Provider',
        'method': 'PUT',
        'name': 'gimo_provider_set',
        'params': [   {   'in': 'body',
                          'name': 'schema_version',
                          'required': False,
                          'type': 'integer'},
                      {'in': 'body', 'name': 'active', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'providers', 'required': True, 'type': 'object'},
                      {'in': 'body', 'name': 'mcp_servers', 'required': False, 'type': 'object'},
                      {'in': 'body', 'name': 'provider_type', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'model_id', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'auth_mode', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'auth_ref', 'required': False, 'type': 'string'},
                      {   'in': 'body',
                          'name': 'last_validated_at',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'effective_state',
                          'required': False,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'capabilities_snapshot',
                          'required': False,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'orchestrator_provider',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'worker_provider',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'orchestrator_model',
                          'required': False,
                          'type': 'string'},
                      {'in': 'body', 'name': 'worker_model', 'required': False, 'type': 'string'}],
        'path': '/ops/provider'},
    {   'description': 'Get Provider Capabilities',
        'method': 'GET',
        'name': 'gimo_provider_capabilities',
        'params': [],
        'path': '/ops/provider/capabilities'},
    {   'description': 'Provider Recommendation',
        'method': 'GET',
        'name': 'gimo_provider_recommendation',
        'params': [],
        'path': '/ops/provider/recommendation'},
    {   'description': 'List Connectors',
        'method': 'GET',
        'name': 'gimo_connectors_list',
        'params': [],
        'path': '/ops/connectors'},
    {   'description': 'Connector Health',
        'method': 'GET',
        'name': 'gimo_connectors_health',
        'params': [   {'in': 'path', 'name': 'connector_id', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'provider_id', 'required': False, 'type': 'string'}],
        'path': '/ops/connectors/{connector_id}/health'},
    {   'description': 'Get Provider Models Catalog',
        'method': 'GET',
        'name': 'gimo_connectors_models',
        'params': [{'in': 'path', 'name': 'provider_type', 'required': True, 'type': 'string'}],
        'path': '/ops/connectors/{provider_type}/models'},
    {   'description': 'Get Active Provider Models',
        'method': 'GET',
        'name': 'gimo_provider_models',
        'params': [],
        'path': '/ops/provider/models'},
    {   'description': 'Install Provider Model',
        'method': 'POST',
        'name': 'gimo_connectors_models_install',
        'params': [   {'in': 'path', 'name': 'provider_type', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'model_id', 'required': True, 'type': 'string'}],
        'path': '/ops/connectors/{provider_type}/models/install'},
    {   'description': 'Get Provider Model Install Job',
        'method': 'GET',
        'name': 'gimo_connectors_install_job',
        'params': [   {'in': 'path', 'name': 'provider_type', 'required': True, 'type': 'string'},
                      {'in': 'path', 'name': 'job_id', 'required': True, 'type': 'string'}],
        'path': '/ops/connectors/{provider_type}/models/install/{job_id}'},
    {   'description': 'Validate Provider Credentials',
        'method': 'POST',
        'name': 'gimo_connectors_validate',
        'params': [   {'in': 'path', 'name': 'provider_type', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'api_key', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'base_url', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'org', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'account', 'required': False, 'type': 'string'}],
        'path': '/ops/connectors/{provider_type}/validate'},
    {   'description': 'Codex Device Login',
        'method': 'POST',
        'name': 'gimo_connectors_codex_login',
        'params': [],
        'path': '/ops/connectors/codex/login'},
    {   'description': 'Claude Login Start',
        'method': 'POST',
        'name': 'gimo_connectors_claude_login',
        'params': [],
        'path': '/ops/connectors/claude/login'},
    {   'description': 'Account Login Start',
        'method': 'POST',
        'name': 'gimo_connectors_account_login',
        'params': [],
        'path': '/ops/connectors/account/login/start'},
    {   'description': 'Account Login Status',
        'method': 'GET',
        'name': 'gimo_connectors_account_status',
        'params': [{'in': 'path', 'name': 'flow_id', 'required': True, 'type': 'string'}],
        'path': '/ops/connectors/account/login/{flow_id}'},
    {   'description': 'Account Refresh',
        'method': 'POST',
        'name': 'gimo_connectors_account_refresh',
        'params': [],
        'path': '/ops/connectors/account/refresh'},
    {   'description': 'Account Logout',
        'method': 'POST',
        'name': 'gimo_connectors_account_logout',
        'params': [],
        'path': '/ops/connectors/account/logout'},
    {   'description': 'Get Config',
        'method': 'GET',
        'name': 'gimo_config_get',
        'params': [],
        'path': '/ops/config'},
    {   'description': 'Set Config',
        'method': 'PUT',
        'name': 'gimo_config_set',
        'params': [   {   'in': 'body',
                          'name': 'default_auto_run',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'draft_cleanup_ttl_days',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'max_concurrent_runs',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'operator_can_generate',
                          'required': False,
                          'type': 'boolean'},
                      {'in': 'body', 'name': 'economy', 'required': False, 'type': 'string'}],
        'path': '/ops/config'},
    {   'description': 'List Mcp Servers',
        'method': 'GET',
        'name': 'gimo_mcp_servers_list',
        'params': [],
        'path': '/ops/config/mcp'},
    {   'description': 'Sync Mcp Tools',
        'method': 'POST',
        'name': 'gimo_mcp_tools_sync',
        'params': [],
        'path': '/ops/config/mcp/sync'},
    {   'description': 'List Tool Registry',
        'method': 'GET',
        'name': 'gimo_tool_registry_list',
        'params': [],
        'path': '/ops/tool-registry'},
    {   'description': 'Get Tool Registry Entry',
        'method': 'GET',
        'name': 'gimo_tool_registry_get',
        'params': [{'in': 'path', 'name': 'tool_name', 'required': True, 'type': 'string'}],
        'path': '/ops/tool-registry/{tool_name}'},
    {   'description': 'Upsert Tool Registry Entry',
        'method': 'PUT',
        'name': 'gimo_tool_registry_upsert',
        'params': [   {'in': 'path', 'name': 'tool_name', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'name', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'description', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'inputs', 'required': False, 'type': 'object'},
                      {'in': 'body', 'name': 'outputs', 'required': False, 'type': 'object'},
                      {'in': 'body', 'name': 'risk', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'estimated_cost', 'required': False, 'type': 'number'},
                      {'in': 'body', 'name': 'requires_hitl', 'required': False, 'type': 'boolean'},
                      {'in': 'body', 'name': 'allowed_roles', 'required': False, 'type': 'array'},
                      {'in': 'body', 'name': 'metadata', 'required': False, 'type': 'object'}],
        'path': '/ops/tool-registry/{tool_name}'},
    {   'description': 'Delete Tool Registry Entry',
        'method': 'DELETE',
        'name': 'gimo_tool_registry_delete',
        'params': [{'in': 'path', 'name': 'tool_name', 'required': True, 'type': 'string'}],
        'path': '/ops/tool-registry/{tool_name}'},
    {   'description': 'Get Policy Config',
        'method': 'GET',
        'name': 'gimo_policy_get',
        'params': [],
        'path': '/ops/policy'},
    {   'description': 'Set Policy Config',
        'method': 'PUT',
        'name': 'gimo_policy_set',
        'params': [{'in': 'body', 'name': 'rules', 'required': False, 'type': 'array'}],
        'path': '/ops/policy'},
    {   'description': 'Policy Decide',
        'method': 'POST',
        'name': 'gimo_policy_decide',
        'params': [],
        'path': '/ops/policy/decide'},
    {   'description': 'Model Recommend',
        'method': 'POST',
        'name': 'gimo_model_recommend',
        'params': [],
        'path': '/ops/model/recommend'},
    {   'description': 'Observability Metrics',
        'method': 'GET',
        'name': 'gimo_observability_metrics',
        'params': [],
        'path': '/ops/observability/metrics'},
    {   'description': 'Observability Traces',
        'method': 'GET',
        'name': 'gimo_observability_traces',
        'params': [{'in': 'query', 'name': 'limit', 'required': False, 'type': 'integer'}],
        'path': '/ops/observability/traces'},
    {   'description': 'Observability Trace Detail',
        'method': 'GET',
        'name': 'gimo_observability_trace_detail',
        'params': [{'in': 'path', 'name': 'trace_id', 'required': True, 'type': 'string'}],
        'path': '/ops/observability/traces/{trace_id}'},
    {   'description': 'Observability Alerts',
        'method': 'GET',
        'name': 'gimo_observability_alerts',
        'params': [],
        'path': '/ops/observability/alerts'},
    {   'description': 'Get Economy Config',
        'method': 'GET',
        'name': 'gimo_mastery_economy_config',
        'params': [],
        'path': '/ops/mastery/config/economy'},
    {   'description': 'Update Economy Config',
        'method': 'POST',
        'name': 'gimo_mastery_economy_update',
        'params': [   {'in': 'body', 'name': 'autonomy_level', 'required': False, 'type': 'string'},
                      {   'in': 'body',
                          'name': 'global_budget_usd',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'provider_budgets',
                          'required': False,
                          'type': 'array'},
                      {   'in': 'body',
                          'name': 'alert_thresholds',
                          'required': False,
                          'type': 'array'},
                      {'in': 'body', 'name': 'cascade', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'eco_mode', 'required': False, 'type': 'string'},
                      {   'in': 'body',
                          'name': 'allow_roi_routing',
                          'required': False,
                          'type': 'boolean'},
                      {'in': 'body', 'name': 'model_floor', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'model_ceiling', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'cache_enabled', 'required': False, 'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'cache_ttl_hours',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'show_cost_predictions',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'provider_model_map',
                          'required': False,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'hardware_thresholds',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'allow_local_override',
                          'required': False,
                          'type': 'boolean'}],
        'path': '/ops/mastery/config/economy'},
    {   'description': 'Get Model Recommendations',
        'method': 'POST',
        'name': 'gimo_mastery_recommend',
        'params': [   {'in': 'body', 'name': 'id', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'type', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'config', 'required': False, 'type': 'object'},
                      {'in': 'body', 'name': 'agent', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'timeout', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'retries', 'required': False, 'type': 'integer'}],
        'path': '/ops/mastery/recommend'},
    {   'description': 'Get Hardware Status',
        'method': 'GET',
        'name': 'gimo_mastery_hardware',
        'params': [],
        'path': '/ops/mastery/hardware'},
    {   'description': 'Get Mastery Status',
        'method': 'GET',
        'name': 'gimo_mastery_status',
        'params': [],
        'path': '/ops/mastery/status'},
    {   'description': 'Get Mastery Recommendations',
        'method': 'GET',
        'name': 'gimo_mastery_recommendations',
        'params': [],
        'path': '/ops/mastery/recommendations'},
    {   'description': 'Predict Workflow Cost',
        'method': 'POST',
        'name': 'gimo_mastery_predict',
        'params': [],
        'path': '/ops/mastery/predict'},
    {   'description': 'Get Mastery Analytics',
        'method': 'GET',
        'name': 'gimo_mastery_analytics',
        'params': [{'in': 'query', 'name': 'days', 'required': False, 'type': 'integer'}],
        'path': '/ops/mastery/analytics'},
    {   'description': 'Get Budget Forecast',
        'method': 'GET',
        'name': 'gimo_mastery_forecast',
        'params': [],
        'path': '/ops/mastery/forecast'},
    {   'description': 'List Skills',
        'method': 'GET',
        'name': 'gimo_skills_list',
        'params': [],
        'path': '/ops/skills'},
    {   'description': 'Create Skill',
        'method': 'POST',
        'name': 'gimo_skills_create',
        'params': [   {'in': 'body', 'name': 'name', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'description', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'command', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'replace_graph', 'required': False, 'type': 'boolean'},
                      {'in': 'body', 'name': 'nodes', 'required': False, 'type': 'array'},
                      {'in': 'body', 'name': 'edges', 'required': False, 'type': 'array'}],
        'path': '/ops/skills'},
    {   'description': 'Get Skill',
        'method': 'GET',
        'name': 'gimo_skills_get',
        'params': [{'in': 'path', 'name': 'skill_id', 'required': True, 'type': 'string'}],
        'path': '/ops/skills/{skill_id}'},
    {   'description': 'Delete Skill',
        'method': 'DELETE',
        'name': 'gimo_skills_delete',
        'params': [{'in': 'path', 'name': 'skill_id', 'required': True, 'type': 'string'}],
        'path': '/ops/skills/{skill_id}'},
    {   'description': 'Generate Description',
        'method': 'POST',
        'name': 'gimo_skills_generate_description',
        'params': [   {'in': 'body', 'name': 'name', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'command', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'nodes', 'required': False, 'type': 'array'},
                      {'in': 'body', 'name': 'edges', 'required': False, 'type': 'array'}],
        'path': '/ops/skills/generate-description'},
    {   'description': 'Execute Skill',
        'method': 'POST',
        'name': 'gimo_skills_execute',
        'params': [   {'in': 'path', 'name': 'skill_id', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'replace_graph', 'required': False, 'type': 'boolean'},
                      {'in': 'body', 'name': 'context', 'required': False, 'type': 'object'}],
        'path': '/ops/skills/{skill_id}/execute'},
    {   'description': 'List Plans',
        'method': 'GET',
        'name': 'gimo_custom_plans_list',
        'params': [],
        'path': '/ops/custom-plans'},
    {   'description': 'Create Plan',
        'method': 'POST',
        'name': 'gimo_custom_plans_create',
        'params': [   {'in': 'body', 'name': 'name', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'description', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'context', 'required': False, 'type': 'object'},
                      {'in': 'body', 'name': 'nodes', 'required': False, 'type': 'array'},
                      {'in': 'body', 'name': 'edges', 'required': False, 'type': 'array'}],
        'path': '/ops/custom-plans'},
    {   'description': 'Get Plan',
        'method': 'GET',
        'name': 'gimo_custom_plans_get',
        'params': [{'in': 'path', 'name': 'plan_id', 'required': True, 'type': 'string'}],
        'path': '/ops/custom-plans/{plan_id}'},
    {   'description': 'Update Plan',
        'method': 'PUT',
        'name': 'gimo_custom_plans_update',
        'params': [   {'in': 'path', 'name': 'plan_id', 'required': True, 'type': 'string'},
                      {'in': 'body', 'name': 'name', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'description', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'nodes', 'required': False, 'type': 'string'},
                      {'in': 'body', 'name': 'edges', 'required': False, 'type': 'string'}],
        'path': '/ops/custom-plans/{plan_id}'},
    {   'description': 'Delete Plan',
        'method': 'DELETE',
        'name': 'gimo_custom_plans_delete',
        'params': [{'in': 'path', 'name': 'plan_id', 'required': True, 'type': 'string'}],
        'path': '/ops/custom-plans/{plan_id}'},
    {   'description': 'Execute Plan',
        'method': 'POST',
        'name': 'gimo_custom_plans_execute',
        'params': [{'in': 'path', 'name': 'plan_id', 'required': True, 'type': 'string'}],
        'path': '/ops/custom-plans/{plan_id}/execute'},
    {   'description': 'List Threads',
        'method': 'GET',
        'name': 'gimo_threads_list',
        'params': [{'in': 'query', 'name': 'workspace_root', 'required': False, 'type': 'string'}],
        'path': '/ops/threads'},
    {   'description': 'Create Thread',
        'method': 'POST',
        'name': 'gimo_threads_create',
        'params': [   {'in': 'query', 'name': 'workspace_root', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'title', 'required': False, 'type': 'string'}],
        'path': '/ops/threads'},
    {   'description': 'Get Thread',
        'method': 'GET',
        'name': 'gimo_threads_get',
        'params': [{'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'}],
        'path': '/ops/threads/{thread_id}'},
    {   'description': 'Add Turn',
        'method': 'POST',
        'name': 'gimo_threads_add_turn',
        'params': [   {'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'agent_id', 'required': True, 'type': 'string'}],
        'path': '/ops/threads/{thread_id}/turns'},
    {   'description': 'Add Item',
        'method': 'POST',
        'name': 'gimo_threads_add_item',
        'params': [   {'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'},
                      {'in': 'path', 'name': 'turn_id', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'type', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'content', 'required': False, 'type': 'string'}],
        'path': '/ops/threads/{thread_id}/turns/{turn_id}/items'},
    {   'description': 'Update Item',
        'method': 'PATCH',
        'name': 'gimo_threads_update_item',
        'params': [   {'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'},
                      {'in': 'path', 'name': 'turn_id', 'required': True, 'type': 'string'},
                      {'in': 'path', 'name': 'item_id', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'delta', 'required': False, 'type': 'string'},
                      {'in': 'query', 'name': 'status', 'required': False, 'type': 'string'}],
        'path': '/ops/threads/{thread_id}/turns/{turn_id}/items/{item_id}'},
    {   'description': 'Fork Thread',
        'method': 'POST',
        'name': 'gimo_threads_fork',
        'params': [   {'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'turn_id', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'title', 'required': False, 'type': 'string'}],
        'path': '/ops/threads/{thread_id}/fork'},
    {   'description': 'Post Message',
        'method': 'POST',
        'name': 'gimo_threads_post_message',
        'params': [   {'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'},
                      {'in': 'query', 'name': 'content', 'required': True, 'type': 'string'}],
        'path': '/ops/threads/{thread_id}/messages'},
    {   'description': 'Get Filtered Openapi',
        'method': 'GET',
        'name': 'gimo_openapi',
        'params': [],
        'path': '/ops/openapi.json'},
    {   'description': 'Ops Event Stream',
        'method': 'GET',
        'name': 'gimo_event_stream',
        'params': [],
        'path': '/ops/stream'},
    # ── SAGP Phase 6: Coverage Push ──────────────────────────────────────
    # Inference endpoints
    {   'description': 'Register model spec for inference',
        'method': 'POST',
        'name': 'gimo_inference_register',
        'params': [{'in': 'body', 'name': 'spec', 'required': True, 'type': 'object'}],
        'path': '/ops/inference/register'},
    {   'description': 'Get inference engine status and session pool',
        'method': 'GET',
        'name': 'gimo_inference_status',
        'params': [],
        'path': '/ops/inference/status'},
    {   'description': 'Get detected compute devices',
        'method': 'GET',
        'name': 'gimo_inference_devices',
        'params': [],
        'path': '/ops/inference/devices'},
    {   'description': 'Get currently loaded model sessions',
        'method': 'GET',
        'name': 'gimo_inference_models',
        'params': [],
        'path': '/ops/inference/models'},
    {   'description': 'Preload model into session pool',
        'method': 'POST',
        'name': 'gimo_inference_load',
        'params': [{'in': 'query', 'name': 'model_id', 'required': True, 'type': 'string'}],
        'path': '/ops/inference/load'},
    {   'description': 'Evict model from session pool',
        'method': 'POST',
        'name': 'gimo_inference_unload',
        'params': [{'in': 'query', 'name': 'model_id', 'required': True, 'type': 'string'}],
        'path': '/ops/inference/unload'},
    {   'description': 'Execute inference request',
        'method': 'POST',
        'name': 'gimo_inference_run',
        'params': [{'in': 'body', 'name': 'request', 'required': True, 'type': 'object'}],
        'path': '/ops/inference/run'},
    {   'description': 'Get inference telemetry metrics',
        'method': 'GET',
        'name': 'gimo_inference_metrics',
        'params': [],
        'path': '/ops/inference/metrics'},
    # App session endpoints
    {   'description': 'List repositories (opaque handles)',
        'method': 'GET',
        'name': 'gimo_app_repos',
        'params': [],
        'path': '/ops/app/repos'},
    {   'description': 'Create file-backed app session',
        'method': 'POST',
        'name': 'gimo_app_sessions_create',
        'params': [],
        'path': '/ops/app/sessions'},
    {   'description': 'Get app session state',
        'method': 'GET',
        'name': 'gimo_app_sessions_get',
        'params': [{'in': 'path', 'name': 'id', 'required': True, 'type': 'string'}],
        'path': '/ops/app/sessions/{id}'},
    {   'description': 'Bind repository to app session',
        'method': 'POST',
        'name': 'gimo_app_sessions_select_repo',
        'params': [{'in': 'path', 'name': 'id', 'required': True, 'type': 'string'},
                   {'in': 'query', 'name': 'repo_handle', 'required': True, 'type': 'string'}],
        'path': '/ops/app/sessions/{id}/repo/select'},
    # Recon endpoints (Cold Room Phase 5.1)
    {   'description': 'List repo files in session',
        'method': 'GET',
        'name': 'gimo_app_recon_list',
        'params': [{'in': 'path', 'name': 'id', 'required': True, 'type': 'string'},
                   {'in': 'query', 'name': 'path', 'required': False, 'type': 'string'}],
        'path': '/ops/app/sessions/{id}/recon/list'},
    {   'description': 'Search repo content in session',
        'method': 'GET',
        'name': 'gimo_app_recon_search',
        'params': [{'in': 'path', 'name': 'id', 'required': True, 'type': 'string'},
                   {'in': 'query', 'name': 'q', 'required': True, 'type': 'string'}],
        'path': '/ops/app/sessions/{id}/recon/search'},
    {   'description': 'Read file with proof in session',
        'method': 'GET',
        'name': 'gimo_app_recon_read',
        'params': [{'in': 'path', 'name': 'id', 'required': True, 'type': 'string'},
                   {'in': 'path', 'name': 'file_handle', 'required': True, 'type': 'string'}],
        'path': '/ops/app/sessions/{id}/recon/read/{file_handle}'},
    # Thread config & proofs
    {   'description': 'Get thread execution proofs',
        'method': 'GET',
        'name': 'gimo_threads_proofs',
        'params': [{'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'}],
        'path': '/ops/threads/{thread_id}/proofs'},
    {   'description': 'Update thread session config',
        'method': 'POST',
        'name': 'gimo_threads_config',
        'params': [{'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'},
                   {'in': 'body', 'name': 'config', 'required': True, 'type': 'object'}],
        'path': '/ops/threads/{thread_id}/config'},
    {   'description': 'Get aggregated thread usage snapshot',
        'method': 'GET',
        'name': 'gimo_threads_usage',
        'params': [{'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'}],
        'path': '/ops/threads/{thread_id}/usage'},
    {   'description': 'Add context elements to thread',
        'method': 'POST',
        'name': 'gimo_threads_add_context',
        'params': [{'in': 'path', 'name': 'thread_id', 'required': True, 'type': 'string'},
                   {'in': 'body', 'name': 'context', 'required': True, 'type': 'object'}],
        'path': '/ops/threads/{thread_id}/context/add'},
    # Checkpoint endpoints
    {   'description': 'List resumable checkpoints',
        'method': 'GET',
        'name': 'gimo_checkpoints_list',
        'params': [],
        'path': '/ops/checkpoints'},
    {   'description': 'Get checkpoint statistics',
        'method': 'GET',
        'name': 'gimo_checkpoints_stats',
        'params': [],
        'path': '/ops/checkpoints/stats'},
    {   'description': 'Get checkpoint details',
        'method': 'GET',
        'name': 'gimo_checkpoints_get',
        'params': [{'in': 'path', 'name': 'checkpoint_id', 'required': True, 'type': 'string'}],
        'path': '/ops/checkpoints/{checkpoint_id}'},
    {   'description': 'Resume operation from checkpoint',
        'method': 'POST',
        'name': 'gimo_checkpoints_resume',
        'params': [{'in': 'path', 'name': 'checkpoint_id', 'required': True, 'type': 'string'}],
        'path': '/ops/checkpoints/{checkpoint_id}/resume'},
    # HITL Action Draft endpoints
    {   'description': 'List action drafts',
        'method': 'GET',
        'name': 'gimo_action_drafts_list',
        'params': [{'in': 'query', 'name': 'status', 'required': False, 'type': 'string'}],
        'path': '/ops/action-drafts'},
    {   'description': 'Get action draft details',
        'method': 'GET',
        'name': 'gimo_action_drafts_get',
        'params': [{'in': 'path', 'name': 'draft_id', 'required': True, 'type': 'string'}],
        'path': '/ops/action-drafts/{draft_id}'},
    {   'description': 'Approve action draft (HITL)',
        'method': 'POST',
        'name': 'gimo_action_drafts_approve',
        'params': [{'in': 'path', 'name': 'draft_id', 'required': True, 'type': 'string'},
                   {'in': 'query', 'name': 'reason', 'required': False, 'type': 'string'}],
        'path': '/ops/action-drafts/{draft_id}/approve'},
    {   'description': 'Reject action draft (HITL)',
        'method': 'POST',
        'name': 'gimo_action_drafts_reject',
        'params': [{'in': 'path', 'name': 'draft_id', 'required': True, 'type': 'string'},
                   {'in': 'query', 'name': 'reason', 'required': False, 'type': 'string'}],
        'path': '/ops/action-drafts/{draft_id}/reject'},
    {   'description': 'Batch approve multiple action drafts',
        'method': 'POST',
        'name': 'gimo_action_drafts_batch_approve',
        'params': [{'in': 'body', 'name': 'draft_ids', 'required': True, 'type': 'array'}],
        'path': '/ops/action-drafts/batch-approve'},
    # Observability extras
    {   'description': 'Get duration statistics',
        'method': 'GET',
        'name': 'gimo_observability_durations',
        'params': [],
        'path': '/ops/observability/durations'},
    {   'description': 'Get rate limit status',
        'method': 'GET',
        'name': 'gimo_observability_rate_limits',
        'params': [],
        'path': '/ops/observability/rate-limits'},
    # Child runs
    {   'description': 'Spawn child run',
        'method': 'POST',
        'name': 'gimo_child_runs_spawn',
        'params': [{'in': 'body', 'name': 'request', 'required': True, 'type': 'object'}],
        'path': '/ops/child-runs/spawn'},
    {   'description': 'Pause child run',
        'method': 'POST',
        'name': 'gimo_child_runs_pause',
        'params': [{'in': 'path', 'name': 'parent_run_id', 'required': True, 'type': 'string'}],
        'path': '/ops/child-runs/{parent_run_id}/pause'},
    {   'description': 'Get children of a run',
        'method': 'GET',
        'name': 'gimo_child_runs_children',
        'params': [{'in': 'path', 'name': 'parent_run_id', 'required': True, 'type': 'string'}],
        'path': '/ops/child-runs/{parent_run_id}/children'},
]
