from __future__ import annotations

# Compatibility shim: Re-export everything from the new models/ directory
# This ensures existing code importing from tools.gimo_server.ops_models continues to work.

try:
    from tools.gimo_server.models import (
        OpsTask, OpsPlan, OpsDraft, OpsApproved, OpsRunStatus, OpsRun,
        OpsConfig, ExecutorReport, OpsCreateDraftRequest, OpsUpdateDraftRequest,
        OpsApproveResponse, OpsCreateRunRequest, ChildRunRequest, RepoEntry, RunEvent, RunLogEntry,
        StatusResponse, UiStatusResponse, VitaminizeResponse,
        SubAgent, SubAgentConfig,
        GimoItemType, GimoItemStatus, GimoThreadStatus, GimoItem, GimoTurn, GimoThread,
        AgentRole, AgentChannel, AgentProfile, AgentActionEvent, AgentInsight,
        ActionDraft, role_profile,
        ProviderType, ProviderEntry, ProviderRoleBinding,
        ProviderRolesConfig, NormalizedModelInfo, ProviderModelsCatalogResponse,
        McpServerConfig, ProviderConfig,
        ProviderValidateRequest, ProviderValidateResponse,
        ProviderModelInstallRequest, ProviderModelInstallResponse,
        ToolEntry, CliDependencyStatus, CliDependencyInstallRequest, CliDependencyInstallResponse,
        CircuitBreakerConfigModel, PHASE4_INTENT_CLASSES,
        ExecutionDecisionCode, IntentDecisionAudit, RuntimePolicyConfig,
        BaselineManifest, PolicyDecision, PolicyRuleMatch, PolicyRule, PolicyConfig,
        TrustRecord, TrustEvent, StrategyFinalStatus, ModelStrategyAudit,
        QualityRating, ProviderBudget,
        CascadeConfig, EcoModeConfig, UserEconomyConfig, CostEvent, BudgetForecast,
        NodeEconomyMetrics, PlanEconomySnapshot, PlanAutonomyUpdateRequest, CascadeResult, CascadeStatsEntry,
        CacheStats, RoiLeaderboardEntry, CostAnalytics, MasteryStatus, IntentClass,
        DelegationStatus, QaVerdict, RepoSnapshot, RepoContext, ContractExecution,
        StrictContract, Delegation, CommandRun, TestRun, DiffRef, Evidence, Failure,
        QaState, GraphState, WorkflowNode, WorkflowEdge, WorkflowGraph,
        WorkflowCheckpoint, WorkflowState, WorkflowExecuteRequest, ContractCheck,
        WorkflowContract, EvalGoldenCase, EvalDataset, EvalJudgeConfig,
        EvalGateConfig, EvalRunRequest, EvalCaseResult, EvalRunReport,
        EvalRunSummary, EvalRunDetail,
        WebSearchProvider, WebSearchQuery, WebSearchResult, WebSearchFusionResponse,
    )
except ImportError:
    from .models import (
        OpsTask, OpsPlan, OpsDraft, OpsApproved, OpsRunStatus, OpsRun,
        OpsConfig, ExecutorReport, OpsCreateDraftRequest, OpsUpdateDraftRequest,
        OpsApproveResponse, OpsCreateRunRequest, ChildRunRequest, RepoEntry, RunEvent, RunLogEntry,
        StatusResponse, UiStatusResponse, VitaminizeResponse,
        SubAgent, SubAgentConfig,
        GimoItemType, GimoItemStatus, GimoThreadStatus, GimoItem, GimoTurn, GimoThread,
        AgentRole, AgentChannel, AgentProfile, AgentActionEvent, AgentInsight,
        ActionDraft, role_profile,
        ProviderType, ProviderEntry, ProviderRoleBinding,
        ProviderRolesConfig, NormalizedModelInfo, ProviderModelsCatalogResponse,
        McpServerConfig, ProviderConfig,
        ProviderValidateRequest, ProviderValidateResponse,
        ProviderModelInstallRequest, ProviderModelInstallResponse,
        ToolEntry, CliDependencyStatus, CliDependencyInstallRequest, CliDependencyInstallResponse,
        CircuitBreakerConfigModel, PHASE4_INTENT_CLASSES,
        ExecutionDecisionCode, IntentDecisionAudit, RuntimePolicyConfig,
        BaselineManifest, PolicyDecision, PolicyRuleMatch, PolicyRule, PolicyConfig,
        TrustRecord, TrustEvent, StrategyFinalStatus, ModelStrategyAudit,
        QualityRating, ProviderBudget,
        CascadeConfig, EcoModeConfig, UserEconomyConfig, CostEvent, BudgetForecast,
        NodeEconomyMetrics, PlanEconomySnapshot, PlanAutonomyUpdateRequest, CascadeResult, CascadeStatsEntry,
        CacheStats, RoiLeaderboardEntry, CostAnalytics, MasteryStatus, IntentClass,
        DelegationStatus, QaVerdict, RepoSnapshot, RepoContext, ContractExecution,
        StrictContract, Delegation, CommandRun, TestRun, DiffRef, Evidence, Failure,
        QaState, GraphState, WorkflowNode, WorkflowEdge, WorkflowGraph,
        WorkflowCheckpoint, WorkflowState, WorkflowExecuteRequest, ContractCheck,
        WorkflowContract, EvalGoldenCase, EvalDataset, EvalJudgeConfig,
        EvalGateConfig, EvalRunRequest, EvalCaseResult, EvalRunReport,
        EvalRunSummary, EvalRunDetail,
        WebSearchProvider, WebSearchQuery, WebSearchResult, WebSearchFusionResponse,
    )

RoleProfile = role_profile
